# Generated by Django 5.2.17 on 2026-09-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('query_type', models.CharField(max_length=32)),
                ('query_input', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=12, null=True)),
                ('display_name', models.TextField(null=True)),
                ('country_code', models.CharField(max_length=4, null=True)),
                ('state_code', models.CharField(max_length=4, null=True)),
                ('raw_json', models.TextField(null=True)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('start_latitude', models.DecimalField(decimal_places=7, max_digits=12)),
                ('start_longitude', models.DecimalField(decimal_places=7, max_digits=12)),
                ('end_latitude', models.DecimalField(decimal_places=7, max_digits=12)),
                ('end_longitude', models.DecimalField(decimal_places=7, max_digits=12)),
                ('distance_miles', models.DecimalField(decimal_places=4, max_digits=14)),
                ('geometry_geojson', models.TextField()),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.IntegerField(db_index=True)),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=511)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(db_index=True, max_length=16)),
                ('rack_id', models.CharField(max_length=63)),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=4, max_digits=10)),
                ('natural_key_hash', models.CharField(db_index=True, max_length=64)),
                ('source_row_id', models.IntegerField()),
                ('source_file', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=12, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='routing_fue_latitud_be23bd_idx'), models.Index(fields=['natural_key_hash', 'retail_price'], name='routing_fue_natural_77aad4_idx')],
                'unique_together': {('natural_key_hash', 'source_row_id', 'source_file')},
            },
        ),
    ]
